version: "3"
services:
  appointmnet-client:
    build: ./appointment-booking-client
    image: appointment-client:v1
  nginx:
    build: ./nginx
    image: appointment-nginx:v1
    depends_on:
      - appointment-api
    ports:
      - 80:80
  appointment-api:
    build: ./appointment-booking-api
    image: appointment-api:v1
    ports:
      - 3001:3001

