version: "3"
services:
  nextjs:
    build: ./appointment-booking-client
    image: gcr.io/appointment-booking-313600/client:v1
  nginx:
    build: ./nginx
    image: gcr.io/appointment-booking-313600/nginx:v1
    depends_on:
      - api
    ports:
      - 80:80
  api:
    build: ./appointment-booking-api
    image: gcr.io/appointment-booking-313600/api:v1
    depends_on:
      - db
    ports:
      - 3001:3001
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: appointments
    volumes:
      - ./appointment-booking-api/pgdata:/var/lib/postgresql/data
    ports:
      - 8000:5432
