version: "3.8"
services:
  nginx:
    build: ./nginx
    depends_on:
      - appointment-client
      - appointment-api
    ports:
      - 80:80
    volumes:
      - ./nginx/dev:/etc/nginx/conf.d
    networks:
      main:
        aliases:
          - nginx
  appointment-client:
    build:
      context: ./Client
      target: development
    volumes:
      - ./Client:/usr/app
    networks:
      main:
        aliases:
          - appointment-client
  appointment-api:
    build:
      context: ./Api
      target: development
    ports:
      - 3001:3001
    volumes:
      - ./Api:/usr/app
    networks:
      main:
        aliases:
          - appointment-api
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: appointments
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      main:
        aliases:
          - db
networks:
  main:
