version: "3.8"
services:
  test-appointment-api:
    build:
      context: ./Api
      target: test
    stdin_open: true
    tty: true
    volumes:
      - ./Api:/usr/app
    depends_on:
      - test-db
    networks:
      main:
        aliases:
          - test-appointment-api
  test-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: appointments
    volumes:
      - ./test-pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      main:
        aliases:
          - db
networks:
  main:
