version: "3"
services:
  nextjs:
    build: ./appointment-booking-client
  nginx:
    build: ./nginx
    depends_on:
      - api
    ports:
      - 80:80
  api:
    build: ./appointment-booking-api
    depends_on:
      - db
    ports:
      - 3001:3001
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: appointments
    volumes:
      - ./appointment-booking-api/pgdata:/var/lib/postgresql/data
    ports:
      - 8000:5432
