version: "3.8"
services:
  nginx:
    build: ./nginx
    image: dockterperry/appointment-nginx:v1
    depends_on:
      - appointment-api
      - appointment-client
    ports:
      - 80:80
      - 443:443
    volumes:
      - /docker-volumes/etc/letsencrypt/live/appointment-booking-example.com/fullchain.pem:/etc/letsencrypt/live/appointment-booking-example.com/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/appointment-booking-example.com/privkey.pem:/etc/letsencrypt/live/appointment-booking-example.com/privkey.pem
      - /etc/ssl:/etc/ssl
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/home/etc
    networks:
      main:
        aliases:
          - nginx
  appointment-client:
    build: ./appointment-booking-client
    image: dockterperry/appointment-client:v1
    ports:
      - 3000:3000
    networks:
      main:
        aliases:
          - appointment-client
  appointment-api:
    build: ./appointment-booking-api
    image: dockterperry/appointment-api:v1
    ports:
      - 3001:3001
    networks:
      main:
        aliases:
          - appointment-api
networks:
  main:
