apiVersion: v1
kind: Deployment
metadata:
  name: appointment-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: appointment-api
    spec:
      containers:
        - name: appointment-api
          image: gcr.io/appointment-booking-313600/api:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
