apiVersion: v1
kind: Deployment
metadata:
  name: appointment-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: appointment-client
    spec:
      containers:
        - name: appointmen-client
          image: gcr.io/appointment-booking-313600/client:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
