version: "3"
services:
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: appointments
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432':'5432'
    web:
      image: appointments-api
      depends_on: 
        - db
      ports:
        - "4000:4000"