apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-client
  template:
    metadata:
      labels:
        app: appointment-client
    spec:
      containers:
        - name: appointment-client
          imagePullPolicy: Never
          image: appointment-client:v1
          ports:
            - containerPort: 3000
          env:
          - name: NEXT_PUBLIC_API_URI
            valueFrom:
              configMapKeyRef:
                name: appointments-configmap
                key: api_address
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-client-service
spec:
  selector:
    app: appointment-client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000